from enum import IntEnum

import pandas as pd
import pytest

from drsa.alternative_set import AlternativesSet
from drsa.criterion import BaseCriterion, Criterion, DecisionCriterion
from drsa.types import ApproximationType, ClassApproximation


class Gender(IntEnum):
    MALE = 0
    FEMALE = 1


class Study(IntEnum):
    BAD = 1
    MEDIUM = 2
    GOOD = 3


class Overall(IntEnum):
    BAD = 1
    MEDIUM = 2
    GOOD = 3


@pytest.fixture
def criteria() -> list[BaseCriterion | Criterion | DecisionCriterion]:
    return [
        BaseCriterion("ID"),
        Criterion("Gender", is_cost=True),
        Criterion("Mathematics", is_cost=False),
        Criterion("Physics", is_cost=False),
        Criterion("Literature", is_cost=False),
        Criterion("AbsentDays", is_cost=True),
        Criterion("Age", is_cost=True),
        DecisionCriterion("Overall"),
    ]


@pytest.fixture
def alternatives(criteria) -> AlternativesSet:
    return AlternativesSet(
        df=pd.DataFrame(
            [
                [21735531, Gender.MALE, Study.MEDIUM, Study.BAD, Study.MEDIUM, 2, 24, Overall.GOOD],
                [7193564, Gender.MALE, Study.GOOD, Study.MEDIUM, Study.BAD, 3, 19, Overall.MEDIUM],
                [15058752, Gender.FEMALE, Study.GOOD, Study.MEDIUM, Study.MEDIUM, 7, 23, Overall.MEDIUM],
                [90260850, Gender.FEMALE, Study.BAD, Study.GOOD, Study.GOOD, 11, 23, Overall.MEDIUM],
                [70603990, Gender.FEMALE, Study.BAD, Study.MEDIUM, Study.GOOD, 0, 19, Overall.MEDIUM],
                [94277922, Gender.FEMALE, Study.BAD, Study.GOOD, Study.BAD, 16, 19, Overall.MEDIUM],
                [91129509, Gender.MALE, Study.GOOD, Study.GOOD, Study.GOOD, 16, 22, Overall.MEDIUM],
                [18975554, Gender.MALE, Study.GOOD, Study.MEDIUM, Study.GOOD, 18, 19, Overall.BAD],
                [11989478, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.MEDIUM, 10, 21, Overall.MEDIUM],
                [26883293, Gender.FEMALE, Study.BAD, Study.BAD, Study.GOOD, 7, 19, Overall.BAD],
                [51324090, Gender.FEMALE, Study.BAD, Study.BAD, Study.BAD, 17, 20, Overall.BAD],
                [63463072, Gender.FEMALE, Study.MEDIUM, Study.BAD, Study.GOOD, 7, 22, Overall.BAD],
                [72357623, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.BAD, 8, 18, Overall.MEDIUM],
                [46252640, Gender.FEMALE, Study.BAD, Study.MEDIUM, Study.MEDIUM, 12, 21, Overall.MEDIUM],
                [96211873, Gender.MALE, Study.MEDIUM, Study.BAD, Study.MEDIUM, 5, 21, Overall.MEDIUM],
                [82903577, Gender.MALE, Study.MEDIUM, Study.MEDIUM, Study.BAD, 14, 21, Overall.BAD],
                [9603997, Gender.FEMALE, Study.GOOD, Study.MEDIUM, Study.BAD, 19, 22, Overall.MEDIUM],
                [57834741, Gender.MALE, Study.BAD, Study.MEDIUM, Study.GOOD, 7, 21, Overall.MEDIUM],
                [66525585, Gender.FEMALE, Study.MEDIUM, Study.GOOD, Study.BAD, 19, 24, Overall.MEDIUM],
                [12509767, Gender.MALE, Study.BAD, Study.GOOD, Study.MEDIUM, 5, 19, Overall.MEDIUM],
                [89725499, Gender.MALE, Study.BAD, Study.BAD, Study.GOOD, 20, 21, Overall.BAD],
                [7053267, Gender.FEMALE, Study.BAD, Study.MEDIUM, Study.MEDIUM, 5, 22, Overall.MEDIUM],
                [20102469, Gender.MALE, Study.MEDIUM, Study.MEDIUM, Study.BAD, 5, 22, Overall.MEDIUM],
                [30442143, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.MEDIUM, 14, 23, Overall.MEDIUM],
                [32294580, Gender.MALE, Study.GOOD, Study.BAD, Study.GOOD, 10, 23, Overall.MEDIUM],
                [12708355, Gender.FEMALE, Study.MEDIUM, Study.GOOD, Study.MEDIUM, 20, 18, Overall.MEDIUM],
                [74228238, Gender.FEMALE, Study.BAD, Study.BAD, Study.GOOD, 0, 23, Overall.BAD],
                [80303623, Gender.MALE, Study.GOOD, Study.BAD, Study.GOOD, 15, 21, Overall.BAD],
                [15642819, Gender.FEMALE, Study.MEDIUM, Study.MEDIUM, Study.MEDIUM, 3, 22, Overall.MEDIUM],
                [44535202, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.BAD, 11, 20, Overall.MEDIUM],
                [94418883, Gender.FEMALE, Study.BAD, Study.BAD, Study.GOOD, 5, 22, Overall.BAD],
                [63181833, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.GOOD, 19, 20, Overall.MEDIUM],
                [10799798, Gender.MALE, Study.GOOD, Study.MEDIUM, Study.BAD, 15, 20, Overall.BAD],
                [28768239, Gender.MALE, Study.MEDIUM, Study.MEDIUM, Study.BAD, 12, 21, Overall.BAD],
                [47095387, Gender.FEMALE, Study.MEDIUM, Study.GOOD, Study.MEDIUM, 6, 23, Overall.GOOD],
                [44740630, Gender.FEMALE, Study.GOOD, Study.BAD, Study.GOOD, 3, 21, Overall.BAD],
                [18071022, Gender.MALE, Study.MEDIUM, Study.BAD, Study.MEDIUM, 6, 21, Overall.MEDIUM],
                [37040537, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.GOOD, 15, 24, Overall.MEDIUM],
                [36199266, Gender.MALE, Study.GOOD, Study.BAD, Study.MEDIUM, 17, 21, Overall.BAD],
                [368600, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.MEDIUM, 4, 20, Overall.GOOD],
                [34387083, Gender.MALE, Study.BAD, Study.BAD, Study.MEDIUM, 20, 21, Overall.BAD],
                [85030153, Gender.FEMALE, Study.BAD, Study.MEDIUM, Study.MEDIUM, 19, 21, Overall.MEDIUM],
                [67665121, Gender.FEMALE, Study.BAD, Study.GOOD, Study.GOOD, 1, 20, Overall.MEDIUM],
                [59587038, Gender.MALE, Study.GOOD, Study.BAD, Study.BAD, 2, 23, Overall.MEDIUM],
                [6629651, Gender.FEMALE, Study.MEDIUM, Study.GOOD, Study.GOOD, 9, 18, Overall.MEDIUM],
                [37457022, Gender.FEMALE, Study.GOOD, Study.MEDIUM, Study.BAD, 4, 20, Overall.MEDIUM],
                [90615554, Gender.FEMALE, Study.MEDIUM, Study.MEDIUM, Study.BAD, 3, 19, Overall.MEDIUM],
                [86152872, Gender.MALE, Study.GOOD, Study.MEDIUM, Study.BAD, 1, 20, Overall.MEDIUM],
                [72883498, Gender.FEMALE, Study.MEDIUM, Study.GOOD, Study.MEDIUM, 18, 20, Overall.MEDIUM],
                [86945887, Gender.MALE, Study.BAD, Study.BAD, Study.MEDIUM, 20, 23, Overall.BAD],
                [14876158, Gender.FEMALE, Study.BAD, Study.GOOD, Study.BAD, 20, 24, Overall.MEDIUM],
                [88301678, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.MEDIUM, 13, 18, Overall.MEDIUM],
                [81643832, Gender.MALE, Study.MEDIUM, Study.BAD, Study.MEDIUM, 0, 19, Overall.GOOD],
                [2407478, Gender.MALE, Study.BAD, Study.GOOD, Study.GOOD, 10, 19, Overall.MEDIUM],
                [38931508, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.BAD, 11, 23, Overall.MEDIUM],
                [81787307, Gender.MALE, Study.MEDIUM, Study.BAD, Study.MEDIUM, 13, 21, Overall.BAD],
                [48024756, Gender.MALE, Study.MEDIUM, Study.BAD, Study.MEDIUM, 14, 25, Overall.BAD],
                [26105440, Gender.FEMALE, Study.MEDIUM, Study.BAD, Study.BAD, 4, 23, Overall.BAD],
                [90358541, Gender.MALE, Study.MEDIUM, Study.MEDIUM, Study.MEDIUM, 10, 20, Overall.MEDIUM],
                [67952786, Gender.MALE, Study.GOOD, Study.BAD, Study.MEDIUM, 6, 19, Overall.MEDIUM],
                [35008421, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.GOOD, 7, 24, Overall.GOOD],
                [65876941, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.MEDIUM, 3, 25, Overall.GOOD],
                [95116681, Gender.FEMALE, Study.BAD, Study.BAD, Study.MEDIUM, 1, 22, Overall.BAD],
                [9015878, Gender.FEMALE, Study.GOOD, Study.BAD, Study.BAD, 10, 20, Overall.BAD],
                [12952614, Gender.FEMALE, Study.BAD, Study.MEDIUM, Study.GOOD, 11, 20, Overall.MEDIUM],
                [42562488, Gender.MALE, Study.MEDIUM, Study.BAD, Study.GOOD, 12, 18, Overall.BAD],
                [14832200, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.GOOD, 3, 22, Overall.GOOD],
                [5345210, Gender.MALE, Study.GOOD, Study.GOOD, Study.GOOD, 9, 19, Overall.MEDIUM],
                [40038652, Gender.MALE, Study.GOOD, Study.MEDIUM, Study.BAD, 16, 19, Overall.BAD],
                [1361482, Gender.MALE, Study.BAD, Study.MEDIUM, Study.MEDIUM, 6, 21, Overall.MEDIUM],
                [90452936, Gender.MALE, Study.GOOD, Study.GOOD, Study.BAD, 10, 19, Overall.MEDIUM],
                [5051970, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.GOOD, 3, 21, Overall.GOOD],
                [41210828, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.MEDIUM, 3, 22, Overall.GOOD],
                [26674284, Gender.MALE, Study.MEDIUM, Study.BAD, Study.BAD, 18, 19, Overall.BAD],
                [65641246, Gender.FEMALE, Study.MEDIUM, Study.MEDIUM, Study.GOOD, 20, 21, Overall.MEDIUM],
                [47814672, Gender.FEMALE, Study.BAD, Study.GOOD, Study.MEDIUM, 19, 21, Overall.MEDIUM],
                [75000013, Gender.MALE, Study.BAD, Study.MEDIUM, Study.GOOD, 2, 20, Overall.MEDIUM],
                [59310282, Gender.MALE, Study.BAD, Study.MEDIUM, Study.BAD, 3, 20, Overall.MEDIUM],
                [59354473, Gender.MALE, Study.GOOD, Study.MEDIUM, Study.BAD, 0, 20, Overall.MEDIUM],
                [64311998, Gender.MALE, Study.GOOD, Study.BAD, Study.GOOD, 16, 20, Overall.BAD],
                [43008725, Gender.FEMALE, Study.BAD, Study.GOOD, Study.MEDIUM, 15, 20, Overall.MEDIUM],
                [90515285, Gender.FEMALE, Study.GOOD, Study.MEDIUM, Study.BAD, 4, 19, Overall.MEDIUM],
                [39775375, Gender.MALE, Study.BAD, Study.GOOD, Study.GOOD, 7, 24, Overall.MEDIUM],
                [38830358, Gender.FEMALE, Study.GOOD, Study.MEDIUM, Study.BAD, 7, 21, Overall.MEDIUM],
                [36423328, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.MEDIUM, 11, 21, Overall.MEDIUM],
                [93881482, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.GOOD, 17, 20, Overall.MEDIUM],
                [14574989, Gender.MALE, Study.MEDIUM, Study.MEDIUM, Study.GOOD, 6, 18, Overall.MEDIUM],
                [53040961, Gender.FEMALE, Study.BAD, Study.GOOD, Study.MEDIUM, 7, 24, Overall.MEDIUM],
                [19091849, Gender.FEMALE, Study.GOOD, Study.MEDIUM, Study.GOOD, 15, 22, Overall.MEDIUM],
                [17886779, Gender.MALE, Study.MEDIUM, Study.GOOD, Study.MEDIUM, 18, 20, Overall.MEDIUM],
                [84985752, Gender.MALE, Study.MEDIUM, Study.BAD, Study.BAD, 14, 19, Overall.BAD],
                [32813492, Gender.FEMALE, Study.MEDIUM, Study.BAD, Study.BAD, 9, 18, Overall.BAD],
                [15475954, Gender.FEMALE, Study.MEDIUM, Study.GOOD, Study.BAD, 4, 19, Overall.MEDIUM],
                [16672684, Gender.FEMALE, Study.BAD, Study.BAD, Study.MEDIUM, 2, 18, Overall.BAD],
                [90694565, Gender.FEMALE, Study.GOOD, Study.GOOD, Study.BAD, 18, 23, Overall.MEDIUM],
                [58429445, Gender.FEMALE, Study.BAD, Study.BAD, Study.MEDIUM, 19, 21, Overall.BAD],
                [84823707, Gender.FEMALE, Study.MEDIUM, Study.MEDIUM, Study.BAD, 6, 22, Overall.MEDIUM],
                [39156594, Gender.MALE, Study.MEDIUM, Study.BAD, Study.GOOD, 11, 21, Overall.BAD],
                [69309102, Gender.MALE, Study.MEDIUM, Study.BAD, Study.MEDIUM, 6, 20, Overall.MEDIUM],
                [23346335, Gender.MALE, Study.MEDIUM, Study.BAD, Study.MEDIUM, 0, 21, Overall.GOOD],
            ],
            index=["Student_" + str(i) for i in range(1, 101)],
            columns=criteria,
        )
    )


@pytest.fixture
def partial_expected_positive_cones():
    return {
        "Student_1": [
            "Student_1",
            "Student_53",
            "Student_100",
        ],
        "Student_2": [
            "Student_2",
        ],
        "Student_3": [
            "Student_3",
            "Student_67",
            "Student_72",
        ],
        "Student_4": [
            "Student_4",
            "Student_43",
            "Student_45",
            "Student_54",
            "Student_67",
            "Student_68",
            "Student_72",
        ],
        "Student_5": [
            "Student_5",
        ],
        "Student_6": [
            "Student_6",
            "Student_13",
            "Student_20",
            "Student_45",
            "Student_52",
            "Student_54",
            "Student_68",
            "Student_71",
            "Student_93",
        ],
        "Student_7": [
            "Student_7",
            "Student_68",
        ],
        "Student_8": [
            "Student_8",
            "Student_68",
        ],
        "Student_9": [
            "Student_9",
            "Student_40",
            "Student_68",
        ],
        "Student_10": [
            "Student_5",
            "Student_10",
            "Student_87",
        ],
    }


@pytest.fixture
def partial_expected_negative_cones():
    return {
        "Student_1": [
            "Student_1",
            "Student_57",
        ],
        "Student_2": [
            "Student_2",
            "Student_11",
            "Student_16",
            "Student_17",
            "Student_23",
            "Student_33",
            "Student_34",
            "Student_46",
            "Student_47",
            "Student_58",
            "Student_64",
            "Student_69",
            "Student_74",
            "Student_78",
            "Student_82",
            "Student_84",
            "Student_91",
            "Student_97",
        ],
        "Student_3": [
            "Student_3",
        ],
        "Student_4": [
            "Student_4",
            "Student_51",
        ],
        "Student_5": [
            "Student_5",
            "Student_10",
            "Student_11",
            "Student_14",
            "Student_22",
            "Student_27",
            "Student_31",
            "Student_42",
            "Student_63",
            "Student_65",
            "Student_96",
        ],
        "Student_6": [
            "Student_6",
            "Student_11",
            "Student_51",
        ],
        "Student_7": [
            "Student_7",
            "Student_17",
            "Student_19",
            "Student_50",
            "Student_51",
            "Student_95",
        ],
        "Student_8": [
            "Student_8",
            "Student_17",
            "Student_21",
            "Student_41",
            "Student_42",
            "Student_50",
            "Student_74",
            "Student_75",
            "Student_96",
        ],
        "Student_9": [
            "Student_9",
            "Student_14",
            "Student_16",
            "Student_19",
            "Student_34",
            "Student_41",
            "Student_42",
            "Student_50",
            "Student_51",
            "Student_55",
            "Student_56",
            "Student_57",
            "Student_76",
            "Student_96",
        ],
        "Student_10": [
            "Student_10",
            "Student_11",
            "Student_96",
        ],
    }


@pytest.fixture
def expected_class_unions_at_least():
    return {
        Overall.GOOD: ClassApproximation(
            Overall.GOOD,
            ApproximationType.AT_LEAST,
            lower_approximation=[
                "Student_1",
                "Student_35",
                "Student_40",
                "Student_53",
                "Student_61",
                "Student_62",
                "Student_67",
                "Student_72",
                "Student_73",
                "Student_100",
            ],
            upper_approximation=[
                "Student_1",
                "Student_35",
                "Student_40",
                "Student_53",
                "Student_61",
                "Student_62",
                "Student_67",
                "Student_72",
                "Student_73",
                "Student_100",
            ],
            objects_that_belong=[
                "Student_1",
                "Student_35",
                "Student_40",
                "Student_53",
                "Student_61",
                "Student_62",
                "Student_67",
                "Student_72",
                "Student_73",
                "Student_100",
            ],
        ),
        Overall.MEDIUM: ClassApproximation(
            Overall.MEDIUM,
            ApproximationType.AT_LEAST,
            lower_approximation=[
                "Student_1",
                "Student_2",
                "Student_3",
                "Student_4",
                "Student_5",
                "Student_6",
                "Student_7",
                "Student_9",
                "Student_13",
                "Student_14",
                "Student_15",
                "Student_18",
                "Student_19",
                "Student_20",
                "Student_22",
                "Student_23",
                "Student_24",
                "Student_25",
                "Student_26",
                "Student_29",
                "Student_30",
                "Student_32",
                "Student_35",
                "Student_37",
                "Student_38",
                "Student_40",
                "Student_43",
                "Student_44",
                "Student_45",
                "Student_46",
                "Student_47",
                "Student_48",
                "Student_49",
                "Student_51",
                "Student_52",
                "Student_53",
                "Student_54",
                "Student_55",
                "Student_59",
                "Student_60",
                "Student_61",
                "Student_62",
                "Student_65",
                "Student_67",
                "Student_68",
                "Student_70",
                "Student_71",
                "Student_72",
                "Student_73",
                "Student_76",
                "Student_77",
                "Student_78",
                "Student_79",
                "Student_81",
                "Student_82",
                "Student_83",
                "Student_84",
                "Student_85",
                "Student_86",
                "Student_87",
                "Student_88",
                "Student_89",
                "Student_90",
                "Student_93",
                "Student_95",
                "Student_97",
                "Student_99",
                "Student_100",
            ],
            upper_approximation=[
                "Student_1",
                "Student_2",
                "Student_3",
                "Student_4",
                "Student_5",
                "Student_6",
                "Student_7",
                "Student_8",
                "Student_9",
                "Student_13",
                "Student_14",
                "Student_15",
                "Student_17",
                "Student_18",
                "Student_19",
                "Student_20",
                "Student_22",
                "Student_23",
                "Student_24",
                "Student_25",
                "Student_26",
                "Student_29",
                "Student_30",
                "Student_32",
                "Student_33",
                "Student_35",
                "Student_37",
                "Student_38",
                "Student_40",
                "Student_42",
                "Student_43",
                "Student_44",
                "Student_45",
                "Student_46",
                "Student_47",
                "Student_48",
                "Student_49",
                "Student_51",
                "Student_52",
                "Student_53",
                "Student_54",
                "Student_55",
                "Student_59",
                "Student_60",
                "Student_61",
                "Student_62",
                "Student_65",
                "Student_67",
                "Student_68",
                "Student_69",
                "Student_70",
                "Student_71",
                "Student_72",
                "Student_73",
                "Student_75",
                "Student_76",
                "Student_77",
                "Student_78",
                "Student_79",
                "Student_81",
                "Student_82",
                "Student_83",
                "Student_84",
                "Student_85",
                "Student_86",
                "Student_87",
                "Student_88",
                "Student_89",
                "Student_90",
                "Student_93",
                "Student_95",
                "Student_97",
                "Student_99",
                "Student_100",
            ],
            objects_that_belong=[
                "Student_1",
                "Student_2",
                "Student_3",
                "Student_4",
                "Student_5",
                "Student_6",
                "Student_7",
                "Student_9",
                "Student_13",
                "Student_14",
                "Student_15",
                "Student_17",
                "Student_18",
                "Student_19",
                "Student_20",
                "Student_22",
                "Student_23",
                "Student_24",
                "Student_25",
                "Student_26",
                "Student_29",
                "Student_30",
                "Student_32",
                "Student_35",
                "Student_37",
                "Student_38",
                "Student_40",
                "Student_42",
                "Student_43",
                "Student_44",
                "Student_45",
                "Student_46",
                "Student_47",
                "Student_48",
                "Student_49",
                "Student_51",
                "Student_52",
                "Student_53",
                "Student_54",
                "Student_55",
                "Student_59",
                "Student_60",
                "Student_61",
                "Student_62",
                "Student_65",
                "Student_67",
                "Student_68",
                "Student_70",
                "Student_71",
                "Student_72",
                "Student_73",
                "Student_75",
                "Student_76",
                "Student_77",
                "Student_78",
                "Student_79",
                "Student_81",
                "Student_82",
                "Student_83",
                "Student_84",
                "Student_85",
                "Student_86",
                "Student_87",
                "Student_88",
                "Student_89",
                "Student_90",
                "Student_93",
                "Student_95",
                "Student_97",
                "Student_99",
                "Student_100",
            ],
        ),
    }


@pytest.fixture
def expected_class_unions_at_most():
    return {
        Overall.BAD: ClassApproximation(
            Overall.BAD,
            ApproximationType.AT_MOST,
            lower_approximation=[
                "Student_10",
                "Student_11",
                "Student_12",
                "Student_16",
                "Student_21",
                "Student_27",
                "Student_28",
                "Student_31",
                "Student_34",
                "Student_36",
                "Student_39",
                "Student_41",
                "Student_50",
                "Student_56",
                "Student_57",
                "Student_58",
                "Student_63",
                "Student_64",
                "Student_66",
                "Student_74",
                "Student_80",
                "Student_91",
                "Student_92",
                "Student_94",
                "Student_96",
                "Student_98",
            ],
            upper_approximation=[
                "Student_8",
                "Student_10",
                "Student_11",
                "Student_12",
                "Student_16",
                "Student_17",
                "Student_21",
                "Student_27",
                "Student_28",
                "Student_31",
                "Student_33",
                "Student_34",
                "Student_36",
                "Student_39",
                "Student_41",
                "Student_42",
                "Student_50",
                "Student_56",
                "Student_57",
                "Student_58",
                "Student_63",
                "Student_64",
                "Student_66",
                "Student_69",
                "Student_74",
                "Student_75",
                "Student_80",
                "Student_91",
                "Student_92",
                "Student_94",
                "Student_96",
                "Student_98",
            ],
            objects_that_belong=[
                "Student_8",
                "Student_10",
                "Student_11",
                "Student_12",
                "Student_16",
                "Student_21",
                "Student_27",
                "Student_28",
                "Student_31",
                "Student_33",
                "Student_34",
                "Student_36",
                "Student_39",
                "Student_41",
                "Student_50",
                "Student_56",
                "Student_57",
                "Student_58",
                "Student_63",
                "Student_64",
                "Student_66",
                "Student_69",
                "Student_74",
                "Student_80",
                "Student_91",
                "Student_92",
                "Student_94",
                "Student_96",
                "Student_98",
            ],
        ),
        Overall.MEDIUM: ClassApproximation(
            Overall.MEDIUM,
            ApproximationType.AT_MOST,
            lower_approximation=[
                "Student_2",
                "Student_3",
                "Student_4",
                "Student_5",
                "Student_6",
                "Student_7",
                "Student_8",
                "Student_9",
                "Student_10",
                "Student_11",
                "Student_12",
                "Student_13",
                "Student_14",
                "Student_15",
                "Student_16",
                "Student_17",
                "Student_18",
                "Student_19",
                "Student_20",
                "Student_21",
                "Student_22",
                "Student_23",
                "Student_24",
                "Student_25",
                "Student_26",
                "Student_27",
                "Student_28",
                "Student_29",
                "Student_30",
                "Student_31",
                "Student_32",
                "Student_33",
                "Student_34",
                "Student_36",
                "Student_37",
                "Student_38",
                "Student_39",
                "Student_41",
                "Student_42",
                "Student_43",
                "Student_44",
                "Student_45",
                "Student_46",
                "Student_47",
                "Student_48",
                "Student_49",
                "Student_50",
                "Student_51",
                "Student_52",
                "Student_54",
                "Student_55",
                "Student_56",
                "Student_57",
                "Student_58",
                "Student_59",
                "Student_60",
                "Student_63",
                "Student_64",
                "Student_65",
                "Student_66",
                "Student_68",
                "Student_69",
                "Student_70",
                "Student_71",
                "Student_74",
                "Student_75",
                "Student_76",
                "Student_77",
                "Student_78",
                "Student_79",
                "Student_80",
                "Student_81",
                "Student_82",
                "Student_83",
                "Student_84",
                "Student_85",
                "Student_86",
                "Student_87",
                "Student_88",
                "Student_89",
                "Student_90",
                "Student_91",
                "Student_92",
                "Student_93",
                "Student_94",
                "Student_95",
                "Student_96",
                "Student_97",
                "Student_98",
                "Student_99",
            ],
            upper_approximation=[
                "Student_2",
                "Student_3",
                "Student_4",
                "Student_5",
                "Student_6",
                "Student_7",
                "Student_8",
                "Student_9",
                "Student_10",
                "Student_11",
                "Student_12",
                "Student_13",
                "Student_14",
                "Student_15",
                "Student_16",
                "Student_17",
                "Student_18",
                "Student_19",
                "Student_20",
                "Student_21",
                "Student_22",
                "Student_23",
                "Student_24",
                "Student_25",
                "Student_26",
                "Student_27",
                "Student_28",
                "Student_29",
                "Student_30",
                "Student_31",
                "Student_32",
                "Student_33",
                "Student_34",
                "Student_36",
                "Student_37",
                "Student_38",
                "Student_39",
                "Student_41",
                "Student_42",
                "Student_43",
                "Student_44",
                "Student_45",
                "Student_46",
                "Student_47",
                "Student_48",
                "Student_49",
                "Student_50",
                "Student_51",
                "Student_52",
                "Student_54",
                "Student_55",
                "Student_56",
                "Student_57",
                "Student_58",
                "Student_59",
                "Student_60",
                "Student_63",
                "Student_64",
                "Student_65",
                "Student_66",
                "Student_68",
                "Student_69",
                "Student_70",
                "Student_71",
                "Student_74",
                "Student_75",
                "Student_76",
                "Student_77",
                "Student_78",
                "Student_79",
                "Student_80",
                "Student_81",
                "Student_82",
                "Student_83",
                "Student_84",
                "Student_85",
                "Student_86",
                "Student_87",
                "Student_88",
                "Student_89",
                "Student_90",
                "Student_91",
                "Student_92",
                "Student_93",
                "Student_94",
                "Student_95",
                "Student_96",
                "Student_97",
                "Student_98",
                "Student_99",
            ],
            objects_that_belong=[
                "Student_2",
                "Student_3",
                "Student_4",
                "Student_5",
                "Student_6",
                "Student_7",
                "Student_8",
                "Student_9",
                "Student_10",
                "Student_11",
                "Student_12",
                "Student_13",
                "Student_14",
                "Student_15",
                "Student_16",
                "Student_17",
                "Student_18",
                "Student_19",
                "Student_20",
                "Student_21",
                "Student_22",
                "Student_23",
                "Student_24",
                "Student_25",
                "Student_26",
                "Student_27",
                "Student_28",
                "Student_29",
                "Student_30",
                "Student_31",
                "Student_32",
                "Student_33",
                "Student_34",
                "Student_36",
                "Student_37",
                "Student_38",
                "Student_39",
                "Student_41",
                "Student_42",
                "Student_43",
                "Student_44",
                "Student_45",
                "Student_46",
                "Student_47",
                "Student_48",
                "Student_49",
                "Student_50",
                "Student_51",
                "Student_52",
                "Student_54",
                "Student_55",
                "Student_56",
                "Student_57",
                "Student_58",
                "Student_59",
                "Student_60",
                "Student_63",
                "Student_64",
                "Student_65",
                "Student_66",
                "Student_68",
                "Student_69",
                "Student_70",
                "Student_71",
                "Student_74",
                "Student_75",
                "Student_76",
                "Student_77",
                "Student_78",
                "Student_79",
                "Student_80",
                "Student_81",
                "Student_82",
                "Student_83",
                "Student_84",
                "Student_85",
                "Student_86",
                "Student_87",
                "Student_88",
                "Student_89",
                "Student_90",
                "Student_91",
                "Student_92",
                "Student_93",
                "Student_94",
                "Student_95",
                "Student_96",
                "Student_97",
                "Student_98",
                "Student_99",
            ],
        ),
    }


@pytest.fixture
def expected_certain_rules(): ...


@pytest.fixture
def expected_possible_rules(): ...
