name: PEP and typing tests

on: push

jobs:
  pep_and_typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python --version

      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/requirements-linting.txt

      - name: Checking with flake8
        run: flake8 drsa/ tests/ --max-line-length=100

      - name: Checking typing
        run: mypy drsa/ tests/ --ignore-missing-imports
